Repository custom-cards/button-card, pull requests merged in 2019-04, with the labels that each got.

#115 configurable confirmation text
  README.md
  button-card.js
Labels: 0.5.0

#116 card-modder-support
  button-card.js
Labels: 0.4.1

#117 Fallback to simple click if longpress is not found
  README.md
  button-card.js
Labels: 0.4.1

#108 Layout
  README.md
  button-card.js
  examples/layout.png
Labels: 0.5.0

#122 typescript refactor
  .gitignore
  README.md
  babel.config.js
  button-card.js
  dist/button-card.js
  examples/README.md
  package-lock.json
  package.json
  rollup.config.js
  src/button-card.ts
  src/const.ts
  src/domain_icons.ts
  src/fire_event.ts
  src/handle-click.ts
  src/has-changed.ts
  src/helpers.ts
  src/long-press.ts
  src/navigate.ts
  src/toggle-entity.ts
  src/turn-on-off-entity.ts
  src/types.ts
  tsconfig.json
Labels: 1.0.0

#123 Haptic
  README.md
  dist/button-card.js
  package-lock.json
  package.json
  src/handle-click.ts
  src/haptic.ts
  src/types.ts
Labels: 1.0.0

#134 Label and templates support
  README.md
  dist/button-card.js
  examples/labels.png
  src/button-card.ts
  src/helpers.ts
  src/styles.ts
  src/types.ts
Labels: 1.4.0
